= devops-stack-module-efs-csi-driver
// Document attributes to replace along the document
:chart-version: 2.3.8
:original-repo-url: https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/386eda75f4d32d134737b35db7e43a1bf3277416

A https://devops-stack.io[DevOps Stack] module to deploy an Amazon EFS Container Storage Interface (CSI) driver.

The EFS CSI Driver chart used by this module is shipped in this repository as well, in order to avoid any unwanted behaviors caused by unsupported versions. 

[cols="1,1,1",options="autowidth,header"]
|===
|Current Chart Version |Original Repository |Default Values
|*{chart-version}* |{original-repo-url}/charts/aws-efs-csi-driver[Chart] |{original-repo-url}/charts/aws-efs-csi-driver/values.yaml[`values.yaml`]
|===

== Usage

This module can be declared by adding the following block on your Terraform configuration:

[source,terraform]
----
module "efs" {
  source = "git::https://github.com/camptocamp/devops-stack-module-efs-csi-driver.git?ref=<RELEASE>"

  cluster_name            = local.cluster_name
  argocd_namespace        = local.argocd_namespace
  efs_file_system_id      = resource.aws_efs_file_system.eks.id
  create_role             = true
  cluster_oidc_issuer_url = module.eks.cluster_oidc_issuer_url

  depends_on = [
    module.argocd_bootstrap,
  ]
}
----

In case you want to create an OIDC assumable IAM role on your own, you'll need to provide the ARN for that role and disable the creation of the role inside of the module as follows:

[source,terraform]
----
module "efs" {
  source = "git::https://github.com/camptocamp/devops-stack-module-efs-csi-driver.git?ref=<RELEASE>"

  cluster_name       = local.cluster_name
  argocd_namespace   = local.argocd_namespace
  efs_file_system_id = resource.aws_efs_file_system.eks.id
  create_role        = false
  iam_role_arn       = module.iam_assumable_role_efs.iam_role_arn

  depends_on = [
    module.argocd_bootstrap,
  ]
}
----

IMPORTANT: The `create_role` variable is required. If passing `iam_role_arn` it should be set as false, otherwise you will need to specify the variable `cluster_oidc_issuer_url` and set it as true.

This module needs to have other resources created externally. You can follow the example bellow:

[source,terraform]
----
resource "aws_efs_file_system" "eks" {
  creation_token = module.eks.cluster_name

  tags = {
    Name = module.eks.cluster_name
  }
}

resource "aws_security_group" "efs_eks" {
  name        = "efs-devops-stack"
  description = "Security group for EFS."
  vpc_id      = module.vpc.vpc_id

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port       = 2049
    to_port         = 2049
    protocol        = "tcp"
    security_groups = [module.eks.node_security_group_id]
  }
}

resource "aws_efs_mount_target" "eks" {
  for_each = toset(module.vpc.private_subnets)

  file_system_id  = resource.aws_efs_file_system.eks.id
  subnet_id       = resource.aws_subnet.private[each.key]
  security_groups = [resource.aws_security_group.efs_eks.id]
}
----

== Technical Reference

=== Dependencies

==== `module.argocd_bootstrap`

This module must be one of the first ones to be deployed and consequently it needs to be deployed after the module `argocd_bootstrap`.

// BEGIN_TF_DOCS
// END_TF_DOCS

=== Reference in table format 

.Show tables
[%collapsible]
====
// BEGIN_TF_TABLES
// END_TF_TABLES
====
